import { SEO } from '@/components/layout/SEO';
import { ProductPage } from '@/components/product/ProductPage';
import { EditorVisual } from '@/components/home/visuals/EditorVisual';
import { CodeBlock } from '@/components/ui/CodeBlock';

const glyph = (
  <svg viewBox="0 0 24 24" fill="none" className="h-5 w-5">
    <path d="M9 8 4 12l5 4M15 8l5 4-5 4M13 6l-2 12" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);

const code = `// Generated by Puku from a single sentence
import { stripe } from '@/lib/stripe'
import { db } from '@/lib/db'

export async function checkout(input: CheckoutInput) {
  const session = await stripe.checkout.sessions.create({
    mode: 'payment',
    line_items: await cart.lineItems(input.cartId),
    customer_email: input.email,
    success_url: input.successUrl,
    cancel_url: input.cancelUrl,
  })
  await db.orders.create({ id: session.id, status: 'pending' })
  return { url: session.url }
}`;

export default function Editor() {
  return (
    <>
      <SEO
        title="Puku Editor — AI-native code editor"
        description="A new AI-native code editor that understands your project, your team, and your intent."
      />
      <ProductPage
        name="Puku Editor"
        color="from-[#A4ABFF] to-[#7C84FF]"
        glyph={glyph}
        tagline="AI-Native Code Editor for Professional Engineers"
        description="Build software using intelligent agents, persistent memory, and project-wide understanding."
        bullets={[
          'AI Chat',
          'Agent Mode',
          'Edit Mode',
          'Persistent Memory',
          'Context Engine',
          'Smart Code Completion',
          'Integrated Terminal',
          'Multi-Model AI',
          'Git Integration',
          'Project Intelligence',
        ]}
        problem={{
          title: 'Editors have not kept up with AI.',
          body:
            'For thirty years, the code editor has been the same: a text buffer, a sidebar, a terminal. AI bolted onto that shape means AI without context. The result is assistants that know nothing about your project, your team, or how your system actually runs. Puku is the editor that finally understands the entire surface area you are working in.',
        }}
        howItWorks={[
          { step: '01', title: 'Open a workspace', body: 'Puku indexes your repo, your infra, your design tokens, and your team decisions in seconds.' },
          { step: '02', title: 'Describe what you want', body: 'A sentence is enough. Puku plans the work, drafts the code, writes the tests, and explains its reasoning.' },
          { step: '03', title: 'Edit together', body: 'Bring teammates and agents into the same buffer. Multi-cursor, multi-agent, in real time.' },
          { step: '04', title: 'Ship from the editor', body: 'Puku CLI and Cloud live inside the editor. Deploy with one keystroke.' },
        ]}
        visual={<EditorVisual />}
        demo={
          <div className="grid grid-cols-1 gap-4 lg:grid-cols-5">
            <div className="lg:col-span-3">
              <CodeBlock
                code={code}
                language="ts"
                filename="services/checkout.ts"
                highlightLines={[4, 5, 6, 7, 8]}
              />
            </div>
            <div className="lg:col-span-2 rounded-2xl border border-border bg-card p-5">
              <div className="text-[11px] uppercase tracking-wider text-ink-dim">Puku plan</div>
              <ol className="mt-3 space-y-2 text-[13.5px] text-ink-muted">
                <li>1 · Scaffold checkout service</li>
                <li>2 · Wire Stripe session</li>
                <li>3 · Persist pending order</li>
                <li>4 · Generate 4 unit tests</li>
                <li>5 · Deploy to edge · 12 regions</li>
              </ol>
              <div className="mt-4 inline-flex items-center gap-2 rounded-md bg-accent/10 px-2 py-1 text-[11.5px] text-accent">
                <span className="h-1.5 w-1.5 rounded-full bg-accent animate-pulse" /> Running
              </div>
            </div>
          </div>
        }
        workflow={[
          'A teammate starts typing in checkout.ts — Puku indexes the change.',
          'You ask Puku to “add a retry policy for failed payments.”',
          'Puku plans the change, edits the file, and proposes tests.',
          'A reviewer leaves a comment in the same buffer.',
          'Puku applies the fix, runs tests, and ships to staging.',
        ]}
        performance={[
          { value: '12ms', label: 'Input latency', hint: 'GPU-rendered at 120Hz' },
          { value: '0.4s', label: 'Cold start to indexed workspace' },
          { value: '< 80MB', label: 'Installer size' },
          { value: '99.99%', label: 'Sync uptime' },
        ]}
        integrations={[
          { name: 'TypeScript', category: 'Language' },
          { name: 'Python', category: 'Language' },
          { name: 'Rust', category: 'Language' },
          { name: 'Go', category: 'Language' },
          { name: 'GitHub', category: 'Source control' },
          { name: 'GitLab', category: 'Source control' },
          { name: 'Postgres', category: 'Database' },
          { name: 'Docker', category: 'Runtime' },
        ]}
        faq={[
          { q: 'Can I import my VS Code setup?', a: 'Yes. Puku imports settings, keybindings, snippets, and most extensions. Your existing themes work out of the box.' },
          { q: 'Is Puku Editor a fork of VS Code?', a: 'No. Puku is built from scratch on a new rendering core. It is open source, native, and free of Electron.' },
          { q: 'Does Puku send my code to a model?', a: 'Only if you ask it to. By default, AI runs on-device. Cloud inference is opt-in, encrypted in transit, and never stored.' },
        ]}
        cta={{ primary: 'Download Puku Editor', secondary: 'Read the docs' }}
        crossLinks={[
          { name: 'Puku CLI', href: '/products/cli', desc: 'Pair the editor with an intelligent terminal.' },
          { name: 'Puku Co-work', href: '/products/cowork', desc: 'Bring teammates and agents into the same buffer.' },
          { name: 'Puku Cloud', href: '/products/cloud', desc: 'Deploy from the editor with one keystroke.' },
        ]}
      />
    </>
  );
}